name: atproto_test
description: This package provides core reusable and useful functionality for testing atproto based packages.
version: 0.2.0
publish_to: none
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  test: ^1.21.0
  xrpc: ^0.2.1
  http: ^0.13.6
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^2.0.0
