name: atproto_annotation
description: >
  Annotations for the atproto_generator.
  This package does nothing without atproto_generator.
version: 0.0.1
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto_annotation
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.0.0

topics:
  - atproto
  - bluesky
  - annotation

dependencies:
  atproto_core: ^0.6.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.0
  import_sorter: ^4.6.0

import_sorter:
  emojis: true
