nsid:
- packages/nsid/**/*
at_uri:
- packages/at_uri/**/*
xrpc:
- packages/xrpc/**/*
atproto_core:
- packages/atproto_core/**/*
lexicon:
- packages/lexicon/**/*
atproto:
- packages/atproto/**/*
bluesky:
- packages/bluesky/**/*
bluesky_cards:
- packages/bluesky_cards/**/*

atproto/lexicon/accounts:
- packages/atproto/lib/src/service/accounts/*.dart
atproto/lexicon/admin:
- packages/atproto/lib/src/service/admin/*.dart
atproto/lexicon/blob:
- packages/atproto/lib/src/service/blob/*.dart
atproto/lexicon/handles:
- packages/atproto/lib/src/service/handles/*.dart
atproto/lexicon/repositories:
- packages/atproto/lib/src/service/repositories/*.dart
atproto/lexicon/reports:
- packages/atproto/lib/src/service/reports/*.dart
atproto/lexicon/servers:
- packages/atproto/lib/src/service/servers/*.dart
atproto/lexicon/sessions:
- packages/atproto/lib/src/service/sessions/*.dart
atproto/lexicon/syncs:
- packages/atproto/lib/src/service/syncs/*.dart

bsky/lexicon/actors:
- packages/bluesky/lib/src/service/actors/*.dart
bsky/lexicon/feeds:
- packages/bluesky/lib/src/service/feeds/*.dart
bsky/lexicon/embed:
- packages/bluesky/lib/src/service/embed/*.dart
bsky/lexicon/graphs:
- packages/bluesky/lib/src/service/graphs/*.dart
bsky/lexicon/notifications:
- packages/bluesky/lib/src/service/notifications/*.dart
bsky/lexicon/systems:
- packages/bluesky/lib/src/service/systems/*.dart
bsky/lexicon/unspecced:
- packages/bluesky/lib/src/service/unspecced/*.dart

test:
- packages/nsid/test/**/*.dart
- packages/at_uri/test/**/*.dart
- packages/xrpc/test/**/*.dart
- packages/atproto_core/test/**/*.dart
- packages/atproto/test/**/*.dart
- packages/bluesky/test/**/*.dart
- packages/bluesky_cards/test/**/*.dart

documentation:
- packages/nsid/CHANGELOG.md
- packages/nsid/README.md
- packages/at_uri/CHANGELOG.md
- packages/at_uri/README.md
- packages/xrpc/CHANGELOG.md
- packages/xrpc/README.md
- packages/atproto_core/CHANGELOG.md
- packages/atproto_core/README.md
- packages/atproto/CHANGELOG.md
- packages/atproto/README.md
- packages/bluesky/CHANGELOG.md
- packages/bluesky/README.md
- packages/bluesky_cards/CHANGELOG.md
- packages/bluesky_cards/README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- SECURITY.md
- STYLEGUIDE.md
