name: atproto_dart
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  github: ^9.12.0
  http: ^1.1.0
  lexicon: ^0.1.2
  pub_api_client: ^2.4.0
  pubspec: ^2.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.2
  melos: ^3.0.1
