name: atproto_dart
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  github: ^9.12.0
  http: ^1.2.1
  lexicon: ^0.2.0
  pub_api_client: ^3.0.0
  pubspec: ^2.3.0
  xrpc: ^0.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.2
  melos: ^6.0.0
  import_sorter: ^4.6.0

import_sorter:
  emojis: true