name: nsid
description: Provide standard NSID object supported by AT Protocol to Dart/Flutter.
version: 0.0.1
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/nsid
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: '>=2.19.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
