name: atproto_core
description: This package provides core reusable and useful functionality for wrapping AT Protocol and related services.
version: 0.5.0
homepage: https://atprotodart.com
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/atproto_core
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ^3.0.0

topics:
  - atproto
  - bluesky
  - api
  - core

dependencies:
  xrpc: ^0.3.0
  at_uri: ^0.2.0
  freezed_annotation: ^2.2.0
  cbor: ^6.0.0
  multiformats: ^0.2.0
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  import_sorter: ^4.6.0

  atproto_test:
    path: ../atproto_test

import_sorter:
  emojis: true
