name: multiformats
description: Provide useful interfaces such a CID used by AT Protocol to Dart/Flutter.
version: 0.0.1
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/multiformats
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  base_codecs: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
