name: bluesky
description: The Easiest and Powerful Dart/Flutter Library for Bluesky Social.
version: 0.2.1
repository: https://github.com/myConsciousness/atproto.dart/tree/main/packages/bluesky
issue_tracker: https://github.com/myConsciousness/atproto.dart/issues
funding:
  - https://github.com/sponsors/myConsciousness
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  atproto_core: ^0.1.0
  atproto: ^0.1.1
  http: ^0.13.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  import_sorter: ^4.6.0
  mockito: ^5.3.2

import_sorter:
  emojis: true
