name: snippets
environment:
  sdk: ^3.0.0

dependencies:
  bluesky:
    path: ../packages/bluesky
  bluesky_text:
    path: ../packages/bluesky_text

dev_dependencies:
  build_web_compilers: ^4.0.0
  lints: ^2.0.1
