name: Update SBOM

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update-sbom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Delete Old Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          if git show-ref --quiet refs/remotes/origin/sbom; then
            git push origin --delete sbom
          fi

      - name: Create New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c sbom
          git push -u origin sbom

      - uses: dart-lang/setup-dart@v1.3
      - name: Install dependencies
        run: dart pub get

      - name: Update SBOM
        run: dart run ./bin/sbom_visualizer.dart myConsciousness atproto.dart
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[Scheduled] SBOM"
          title: "[Scheduled] SBOM"
          branch: sbom
          base: main
          labels: Github Actions
          assignees: "${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
