name: Validate Dependency

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "packages/*/pubspec.yaml"

jobs:
  validate-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Validate Dependencies
        run: dart run ./bin/validate_dependencies.dart
